### ISSUE TITLE
华为meta9点击录制就报错

### ISSUE THREAD

**Issue by nidewole** [qqchenjian318/VideoEditor-For-Android#10]
华为meta9点击录制就报错如下：
FATAL EXCEPTION: GLThread 816
Process: com.example.cj.videoeditor, PID: 17256
java.lang.RuntimeException: Fail to connect to camera service
at android.hardware.Camera.(Camera.java:571)
at android.hardware.Camera.open(Camera.java:415)
at com.example.cj.videoeditor.camera.CameraController.open(CameraController.java:46)
at com.example.cj.videoeditor.widget.CameraView.open(CameraView.java:61)
at com.example.cj.videoeditor.widget.CameraView.onSurfaceCreated(CameraView.java:80)

**Comment by qqchenjian318** [comment]
是否是因为没有camera权限的原因

**Comment by hzhou81** [comment]
华为手机要在权限中信任本程序
