### ISSUE TITLE
Android 4.4 Crash

### ISSUE THREAD

**Issue by addskya** [qqchenjian318/VideoEditor-For-Android#11]
FATAL EXCEPTION: pool-3-thread-2
Process: com.example.cj.videoeditor, PID: 30756
java.nio.BufferOverflowException
    at java.nio.ByteBuffer.put(ByteBuffer.java:753)
    at com.example.cj.videoeditor.mediacodec.VideoClipper.startAudioCodec(VideoClipper.java:276)
    at com.example.cj.videoeditor.mediacodec.VideoClipper.access$400(VideoClipper.java:30)
    at com.example.cj.videoeditor.mediacodec.VideoClipper$2.run(VideoClipper.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

**Comment by qqchenjian318** [comment]
应该跟视频源有关系，报错是在音频处理的时候，如果发现是单声道音频的话，会自动转成多声道，但是ByteBuffer的缓冲区大小缺不够导致的

**Comment by addskya** [comment]
那应该如何处理呢,我将
MediaFormat format = MediaFormat.createAudioFormat("audio/mp4a-latm", 44100, /*channelCount*/2);//这里一定要注意声道的问题 
修改为:  channelCount ==> 1,还是会Crash
