### ISSUE TITLE
添加滤镜崩溃

### ISSUE THREAD

**Issue by mghxz252** [qqchenjian318/VideoEditor-For-Android#20]
添加滤镜后，会崩溃
E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-2
                                                                          Process: com.example.cj.videoeditor, PID: 4850
                                                                          java.nio.BufferOverflowException
                                                                              at java.nio.ByteBuffer.put(ByteBuffer.java:544)
                                                                              at com.example.cj.videoeditor.mediacodec.VideoClipper.startAudioCodec(VideoClipper.java:274)
                                                                              at com.example.cj.videoeditor.mediacodec.VideoClipper.access$400(VideoClipper.java:30)
                                                                              at com.example.cj.videoeditor.mediacodec.VideoClipper$2.run(VideoClipper.java:174)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:760)

**Comment by DaFengZhi** [comment]
兄弟这个问题解决了没？
我也遇到这个问题了。
