### ISSUE TITLE
4.3以上的问题

### ISSUE THREAD

**Issue by liuswong** [qqchenjian318/VideoEditor-For-Android#35]
4.3.1和4.4.2的都不能使用!报错
java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                                at android.media.AudioRecord.startRecording(AudioRecord.java:506)
                                                                                at com.example.cj.videoeditor.record.video.VideoEncoderCore.<init>(VideoEncoderCore.java:96)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.prepareEncoder(TextureMovieEncoder.java:426)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.handleStartRecording(TextureMovieEncoder.java:334)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.access$000(TextureMovieEncoder.java:64)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:298)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.run(TextureMovieEncoder.java:265)
                                                                                at java.lang.Thread.run(Thread.java:841)
还有这种
   java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                                at android.media.AudioRecord.startRecording(AudioRecord.java:506)
                                                                                at com.example.cj.videoeditor.record.video.VideoEncoderCore.<init>(VideoEncoderCore.java:96)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.prepareEncoder(TextureMovieEncoder.java:426)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.handleStartRecording(TextureMovieEncoder.java:334)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.access$000(TextureMovieEncoder.java:64)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:298)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.run(TextureMovieEncoder.java:265)
                                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by qqchenjian318** [comment]
1、可能是没给相关权限
2、可能是之前录制申请的资源没有释放成功 、
https://blog.csdn.net/wyyl1/article/details/45719099这篇文章可能对你有用
