### ISSUE TITLE
录制后  退出  再进入 会崩溃

### ISSUE THREAD

**Issue by GuBYg** [qqchenjian318/VideoEditor-For-Android#4]
录制后  退出  再进入 会崩溃

**Comment by qqchenjian318** [comment]
我这边未能复现，能提供一下错误日志吗

**Comment by GuBYg** [comment]
@qqchenjian318   是因为退出的时候  没有回收camera  再次进入的时候  重新 连接camera的时候  出错


public void onDestroy() {
        if (mCamera != null) {
            mCamera.stopPreview();
            mCamera.release();
            mCamera=null;
        }
    }

在网上找到这个解决方法  我也试了添加后  再没出现这个bug

**Comment by GuBYg** [comment]
------------------ 原始邮件 ------------------
发件人: "qqchenjian318";<notifications@github.com>;
发送时间: 2017年11月29日(星期三) 上午9:42
收件人: "qqchenjian318/VideoEditor-For-Android"<VideoEditor-For-Android@noreply.github.com>;
抄送: "莫じヅ語"<970972963@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [qqchenjian318/VideoEditor-For-Android] 录制后 退出 再进入 会崩溃 (#4)




我这边未能复现，能提供一下错误日志吗

**Comment by nidewole** [comment]
华为meta9点击录制就报错如下：
FATAL EXCEPTION: GLThread 816                                                                           
 Process: com.example.cj.videoeditor, PID: 17256
 java.lang.RuntimeException: Fail to connect to camera service
at android.hardware.Camera.<init>(Camera.java:571)
 at android.hardware.Camera.open(Camera.java:415)
 at com.example.cj.videoeditor.camera.CameraController.open(CameraController.java:46)
at com.example.cj.videoeditor.widget.CameraView.open(CameraView.java:61)
  at com.example.cj.videoeditor.widget.CameraView.onSurfaceCreated(CameraView.java:80)
