### ISSUE TITLE
录制打开出现崩溃还有就是6.0运行时权限未添加

### ISSUE THREAD

**Issue by HashWaney** [qqchenjian318/VideoEditor-For-Android#44]
E/AndroidRuntime: FATAL EXCEPTION: TextureMovieEncoder
                                                                            Process: com.example.cj.videoeditor, PID: 14649
                                                                            java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                                at android.media.AudioRecord.startRecording(AudioRecord.java:989)
                                                                                at com.example.cj.videoeditor.record.video.VideoEncoderCore.<init>(VideoEncoderCore.java:96)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.prepareEncoder(TextureMovieEncoder.java:426)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.handleStartRecording(TextureMovieEncoder.java:334)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.access$000(TextureMovieEncoder.java:64)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:298)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at com.example.cj.videoeditor.record.video.TextureMovieEncoder.run(TextureMovieEncoder.java:265)
                                                                                at java.lang.Thread.run(Thread.java:776)

**Comment by qqchenjian318** [comment]
项目比较老，并没有加上权限校验相关。上述错误在这篇文章有所讲解 https://blog.csdn.net/wyyl1/article/details/45719099
